packages:
  - contracts
  - frontend
  - og-bridge
  - og-compute-bridge
allowBuilds:
  '@reown/appkit': true
  blake-hash: true
  bufferutil: true
  es5-ext: true
  esbuild: true
  keccak: true
  protobufjs: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
