"""
gnubg_client.py

A wrapper around the GNU Backgammon (gnubg) CLI engine.
Uses the `pexpect` library to spawn a gnubg process and interact with it
by sending commands and parsing the textual output.
"""
import pexpect
import re
from typing import List, Optional
from app.game_state import GameState

class GNUBGClient:
    """
    Manages a subprocess running the `gnubg` command line interface.
    """
    def __init__(self):
        """Initialize the client state without starting the process."""
        self.process = None
        self.gnubg_turn = False
        self._is_game_over = False
        self._winner = None

    def start(self):
        """
        Start the gnubg CLI in a child process using pexpect.
        Configures the engine to disable sounds and sets the user as a human player.
        """
        # Start gnubg in text mode (-t) with a 5 second timeout for expectations
        self.process = pexpect.spawn('gnubg -t', encoding='utf-8', timeout=5)

        # The prompt usually looks like "(No game) " or "(jules) " or "(gnubg) "
        self.process.expect(r'\) ')

        # Disable audio to avoid ALSA errors in headless environments
        self.process.sendline('set sound enable no')
        self.process.expect(r'\) ')

        # Register the human player 'jules'
        self.process.sendline('set player jules human')
        self.process.expect(r'\) ')

    def stop(self):
        """
        Gracefully terminate the gnubg subprocess.
        """
        if self.process:
            self.process.sendline('quit')
            self.process.close()

    def new_match(self, length: int):
        """
        Command the engine to start a new match.

        Args:
            length (int): The number of points to play to.
        """
        self.process.sendline(f'new match {length}')
        self._is_game_over = False
        self._winner = None
        self.process.expect(r'\) ')

    def get_agent_move(self, board_state: GameState, dice: List[int]) -> Optional[str]:
        """
        Ask the engine for its move given the current dice.

        Args:
            board_state (GameState): The current game state (used for reference, sync handled internally).
            dice (List[int]): A list containing the two dice values rolled.

        Returns:
            Optional[str]: The move string returned by gnubg (e.g. "8/4 6/4"), or None if parsing failed.
        """
        # Set the dice for gnubg's turn
        self.process.sendline(f'set dice {dice[0]} {dice[1]}')
        self.process.expect(r'\) ')

        # Tell gnubg to compute and play its move
        self.process.sendline('play')
        self.process.expect(r'\) ')

        # Read the output generated by the 'play' command
        output = self.process.before

        # Parse the move from the engine's text output
        # Example output: "gnubg moves 8/4 6/4."
        match = re.search(r'gnubg moves (.*?)\.', output)
        if match:
            # Check if this move won the game for the agent
            if 'wins a' in output or 'wins the game' in output or 'wins the match' in output:
                self._is_game_over = True
                self._winner = 1 # gnubg is player 2 (index 1)
            return match.group(1).strip()

        return None

    def submit_move(self, board_state: GameState, dice: List[int], move: str):
        """
        Submit a human player's move to the gnubg engine to keep the internal state in sync.

        Args:
            board_state (GameState): The current state.
            dice (List[int]): The dice rolled for the human turn.
            move (str): The string representation of the move (e.g., "24/18").
        """
        # Set the dice for the human turn
        self.process.sendline(f'set dice {dice[0]} {dice[1]}')
        self.process.expect(r'\) ')

        # Input the move
        self.process.sendline(f'move {move}')
        self.process.expect(r'\) ')

        # Check if the human's move won the game
        output = self.process.before
        if 'wins a' in output or 'wins the game' in output or 'wins the match' in output:
            self._is_game_over = True
            self._winner = 0 # human is player 1 (index 0)

    def is_game_over(self) -> bool:
        """Return True if the match has concluded."""
        return self._is_game_over

    def winner(self) -> Optional[int]:
        """Return the index of the winner (0=human, 1=gnubg) or None if not over."""
        return self._winner
