// gen_fixtures.ts — deterministically derives two ed25519 session keypairs,
// signs the canonical ResultMsg bytes for a fixed test match, and prints
// Move byte-vector/address constants to embed in tests/match_tests.move.
//
// Run: node --experimental-strip-types sui/scripts/gen_fixtures.ts
//
// The struct shape here (field names, order, types) MUST exactly match
// chaingammon::match's ResultMsg struct in sources/match.move — BCS encodes
// struct fields in declaration order with no field-name framing, so any
// mismatch (order, or vector<u8> vs fixed address) produces different bytes
// and the embedded signatures will fail ed25519_verify in Move.
import { bcs } from "@mysten/sui/bcs";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";

// Fixed 32-byte seeds — deterministic and public on purpose (test fixtures
// only, never used for real funds).
const SEED_A = new Uint8Array(32).fill(0xa1);
const SEED_B = new Uint8Array(32).fill(0xb2);

const DOMAIN = new TextEncoder().encode("Chaingammon:result-sui-hvh");
const APP_MATCH_ID = new TextEncoder().encode("chaingammon-test-match-001");
// Move test address `@0xA11CE` (matches sui/move/chaingammon/tests/agent_tests.move's
// OWNER constant), encoded as a full 32-byte address.
const WINNER_HEX = "0x" + "0".repeat(64 - "a11ce".length) + "a11ce";

const ResultMsg = bcs.struct("ResultMsg", {
  domain: bcs.byteVector(),
  app_match_id: bcs.byteVector(),
  winner: bcs.Address,
});

function toMoveHex(bytes: Uint8Array): string {
  return 'x"' + Buffer.from(bytes).toString("hex") + '"';
}

async function main() {
  const kpA = Ed25519Keypair.fromSecretKey(SEED_A);
  const kpB = Ed25519Keypair.fromSecretKey(SEED_B);

  const msgBytes = ResultMsg.serialize({
    domain: DOMAIN,
    app_match_id: APP_MATCH_ID,
    winner: WINNER_HEX,
  }).toBytes();

  const sigA = await kpA.sign(msgBytes);
  const sigB = await kpB.sign(msgBytes);
  const pkA = kpA.getPublicKey().toRawBytes();
  const pkB = kpB.getPublicKey().toRawBytes();

  console.log("// Generated by sui/scripts/gen_fixtures.ts — do not hand-edit.");
  console.log(`// msg bytes: ${toMoveHex(msgBytes)} (len=${msgBytes.length})`);
  console.log(`const DOMAIN: vector<u8> = b"Chaingammon:result-sui-hvh";`);
  console.log(`const APP_MATCH_ID: vector<u8> = b"chaingammon-test-match-001";`);
  console.log(`const WINNER: address = @${WINNER_HEX};`);
  console.log(`const SESSION_PK_A: vector<u8> = ${toMoveHex(pkA)};`);
  console.log(`const SESSION_PK_B: vector<u8> = ${toMoveHex(pkB)};`);
  console.log(`const SIG_A: vector<u8> = ${toMoveHex(sigA)};`);
  console.log(`const SIG_B: vector<u8> = ${toMoveHex(sigB)};`);
  console.log(`// bad signature fixture (sig_a signed by kpB's key instead of kpA's — same message, wrong signer):`);
  const sigWrong = await kpB.sign(msgBytes);
  console.log(`const SIG_A_WRONG_SIGNER: vector<u8> = ${toMoveHex(sigWrong)};`);
}

main();
