// rated_match_client.ts — the on-chain half of rated play (Task 6): open,
// join, roll (on-chain dice via sui::random), and cosigned settle,
// wrapping chaingammon::game_match for the app.
//
// Mirrors sui/scripts/gen_fixtures.ts's ResultMsg BCS schema exactly — this
// is the same canonical-result-bytes construction chaingammon::game_match's
// `canonical_result_bytes` reconstructs on-chain, so a session key's
// signature over these bytes verifies with `ed25519_verify` there. Any
// drift between this schema and game_match.move's ResultMsg struct (field
// order, types, or the domain string) breaks settlement silently until
// tested — see game_match_tests.move's header comment for why fixtures are
// always generated by actually running code, never hand-derived.
"use client";

import { bcs } from "@mysten/sui/bcs";
import { SuiJsonRpcClient } from "@mysten/sui/jsonRpc";
import { Transaction } from "@mysten/sui/transactions";
import type { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import type { LocalnetConfig } from "./sui_client";

const DOMAIN = new TextEncoder().encode("Chaingammon:result-sui-hvh");

const ResultMsg = bcs.struct("ResultMsg", {
  domain: bcs.byteVector(),
  app_match_id: bcs.byteVector(),
  winner: bcs.Address,
});

/** Same canonical bytes chaingammon::game_match::canonical_result_bytes reconstructs on-chain. */
export function canonicalResultBytes(appMatchId: Uint8Array, winner: string): Uint8Array {
  return ResultMsg.serialize({ domain: DOMAIN, app_match_id: appMatchId, winner }).toBytes();
}

const clients = new Map<string, SuiJsonRpcClient>();
function getClient(rpcUrl: string): SuiJsonRpcClient {
  let client = clients.get(rpcUrl);
  if (!client) {
    client = new SuiJsonRpcClient({ url: rpcUrl, network: "localnet" });
    clients.set(rpcUrl, client);
  }
  return client;
}

export interface OpenResult {
  matchObjectId: string;
}

/** Creator: lock `stakeMist` and open a rated match. Returns the new shared Match's object id. */
export async function openRatedMatch(
  config: LocalnetConfig,
  signer: Ed25519Keypair,
  appMatchId: Uint8Array,
  sessionPubkey: Uint8Array,
  stakeMist: bigint,
  profileId: string | null,
): Promise<OpenResult> {
  const client = getClient(config.rpcUrl);
  const address = signer.getPublicKey().toSuiAddress();
  const tx = new Transaction();
  tx.setSender(address);
  const [stakeCoin] = tx.splitCoins(tx.gas, [tx.pure.u64(stakeMist)]);
  tx.moveCall({
    target: `${config.packageId}::game_match::open`,
    arguments: [
      stakeCoin,
      tx.pure.vector("u8", Array.from(sessionPubkey)),
      tx.pure.bool(true),
      tx.pure.vector("u8", Array.from(appMatchId)),
      tx.pure.option("id", null),
      tx.pure.option("id", profileId),
    ],
  });
  const result = await client.signAndExecuteTransaction({
    transaction: tx,
    signer,
    options: { showObjectChanges: true },
  });
  await client.waitForTransaction({ digest: result.digest });

  const created = (result.objectChanges ?? []).find(
    (c) => c.type === "created" && "objectType" in c && c.objectType === `${config.packageId}::game_match::Match`,
  ) as { objectId: string } | undefined;
  if (!created) throw new Error(`open(): no Match object in objectChanges — digest ${result.digest}`);
  return { matchObjectId: created.objectId };
}

/** Joiner: lock a matching stake and join an OPEN match by its object id. */
export async function joinRatedMatch(
  config: LocalnetConfig,
  signer: Ed25519Keypair,
  matchObjectId: string,
  sessionPubkey: Uint8Array,
  stakeMist: bigint,
  profileId: string | null,
): Promise<void> {
  const client = getClient(config.rpcUrl);
  const address = signer.getPublicKey().toSuiAddress();
  const tx = new Transaction();
  tx.setSender(address);
  const [stakeCoin] = tx.splitCoins(tx.gas, [tx.pure.u64(stakeMist)]);
  tx.moveCall({
    target: `${config.packageId}::game_match::join`,
    arguments: [
      tx.object(matchObjectId),
      stakeCoin,
      tx.pure.vector("u8", Array.from(sessionPubkey)),
      tx.pure.option("id", null),
      tx.pure.option("id", profileId),
    ],
  });
  const result = await client.signAndExecuteTransaction({ transaction: tx, signer });
  await client.waitForTransaction({ digest: result.digest });
}

export interface DiceRoll {
  turnIndex: number;
  d1: number;
  d2: number;
}

/**
 * Submit `game_match::roll` — must only be called by the side whose turn it
 * is per `turn_index` parity (even -> creator, odd -> joiner); Move aborts
 * (EWrongRoller) otherwise. Reads the resulting DiceRolled event directly
 * from this transaction's own response — authoritative, since this call
 * itself produced it.
 */
export async function rollOnChainDice(
  config: LocalnetConfig,
  signer: Ed25519Keypair,
  matchObjectId: string,
): Promise<DiceRoll> {
  const client = getClient(config.rpcUrl);
  const address = signer.getPublicKey().toSuiAddress();
  const tx = new Transaction();
  tx.setSender(address);
  tx.moveCall({
    target: `${config.packageId}::game_match::roll`,
    arguments: [tx.object(matchObjectId), tx.object.random()],
  });
  const result = await client.signAndExecuteTransaction({
    transaction: tx,
    signer,
    options: { showEvents: true },
  });
  await client.waitForTransaction({ digest: result.digest });
  return diceRollFromEvents(config, result.events);
}

function diceRollFromEvents(config: LocalnetConfig, events: unknown[] | null | undefined): DiceRoll {
  const type = `${config.packageId}::game_match::DiceRolled`;
  const ev = (events ?? []).find((e) => (e as { type?: string }).type === type) as
    | { parsedJson: { turn_index: string | number; d1: string | number; d2: string | number } }
    | undefined;
  if (!ev) throw new Error("roll(): no DiceRolled event in transaction response");
  return {
    turnIndex: Number(ev.parsedJson.turn_index),
    d1: Number(ev.parsedJson.d1),
    d2: Number(ev.parsedJson.d2),
  };
}

/**
 * Independently fetch the DiceRolled event for a specific turn — used by
 * the peer who did NOT submit the `roll` transaction, so both sides learn
 * d1/d2 from the chain itself rather than trusting a value relayed over
 * WebRTC (which would defeat the entire point of on-chain dice). Polls
 * briefly since the event may not be indexed the instant the roller's
 * transaction lands.
 */
export async function waitForDiceRoll(
  config: LocalnetConfig,
  matchObjectId: string,
  turnIndex: number,
  timeoutMs = 30_000,
): Promise<DiceRoll> {
  const client = getClient(config.rpcUrl);
  const type = `${config.packageId}::game_match::DiceRolled`;
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const page = await client.queryEvents({
      query: { MoveEventType: type },
      order: "descending",
      limit: 20,
    });
    for (const ev of page.data) {
      const parsed = ev.parsedJson as { match_uid: string; turn_index: string | number; d1: string | number; d2: string | number };
      if (parsed.match_uid === matchObjectId && Number(parsed.turn_index) === turnIndex) {
        return { turnIndex, d1: Number(parsed.d1), d2: Number(parsed.d2) };
      }
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`waitForDiceRoll: turn ${turnIndex} never appeared within ${timeoutMs}ms`);
}

/** Either side (or a sponsor): submit the cosigned result, paying the winner. */
export async function settleRatedMatch(
  config: LocalnetConfig,
  signer: Ed25519Keypair,
  matchObjectId: string,
  winner: string,
  sigA: Uint8Array,
  sigB: Uint8Array,
): Promise<void> {
  const client = getClient(config.rpcUrl);
  const address = signer.getPublicKey().toSuiAddress();
  const tx = new Transaction();
  tx.setSender(address);
  tx.moveCall({
    target: `${config.packageId}::game_match::settle_cosigned`,
    arguments: [
      tx.object(matchObjectId),
      tx.pure.address(winner),
      tx.pure.vector("u8", Array.from(sigA)),
      tx.pure.vector("u8", Array.from(sigB)),
    ],
  });
  const result = await client.signAndExecuteTransaction({ transaction: tx, signer });
  await client.waitForTransaction({ digest: result.digest });
}

/**
 * Same as `settleRatedMatch`, plus updates both players' `HumanProfile`
 * ELO — requires the match to have recorded both profile ids at open/join
 * time (see `sui_client.ts`'s `profileIdFor`).
 */
export async function settleRatedMatchWithProfiles(
  config: LocalnetConfig,
  signer: Ed25519Keypair,
  matchObjectId: string,
  winner: string,
  sigA: Uint8Array,
  sigB: Uint8Array,
  profileAId: string,
  profileBId: string,
): Promise<void> {
  const client = getClient(config.rpcUrl);
  const address = signer.getPublicKey().toSuiAddress();
  const tx = new Transaction();
  tx.setSender(address);
  tx.moveCall({
    target: `${config.packageId}::game_match::settle_cosigned_with_profiles`,
    arguments: [
      tx.object(matchObjectId),
      tx.pure.address(winner),
      tx.pure.vector("u8", Array.from(sigA)),
      tx.pure.vector("u8", Array.from(sigB)),
      tx.object(profileAId),
      tx.object(profileBId),
    ],
  });
  const result = await client.signAndExecuteTransaction({ transaction: tx, signer });
  await client.waitForTransaction({ digest: result.digest });
}
